/* Generated By:JavaCC: Do not edit this line. MyLanguagerTreeConstants.java Version 5.0 */
package project;

public interface MyLanguagerTreeConstants
{
  public int JJTARITHMETICOPERATION = 0;
  public int JJTRELATIONALOPERATION = 1;
  public int JJTLOGICALOPERATION = 2;
  public int JJTARITHMETICSTATMENT = 3;
  public int JJTCONDITION = 4;
  public int JJTLOGICALSTATMENT = 5;
  public int JJTIFSTATEMENT = 6;
  public int JJTEXP = 7;
  public int JJTDATATYPE = 8;
  public int JJTCODE = 9;
  public int JJTSTART = 10;


  public String[] jjtNodeName = {
    "ArithmeticOperation",
    "RelationalOperation",
    "LogicalOperation",
    "arithmeticStatment",
    "CONDITION",
    "logicalStatment",
    "IfStatement",
    "exp",
    "dataType",
    "code",
    "Start",
  };
}
/* JavaCC - OriginalChecksum=deacba809b11ef77f78b6433194bcb8a (do not edit this line) */
